dist: trusty
language: java
install: true

addons:
  ssh_known_hosts: ec2-34-235-168-107.compute-1.amazonaws.com

jdk:
  - openjdk8

script:
  - ./gradlew build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dynamic-api .
  - docker images
  - docker tag dynamic-api $DOCKER_USERNAME/dynamic-api
  - docker push $DOCKER_USERNAME/dynamic-api
  - docker push 348892447740.dkr.ecr.us-east-1.amazonaws.com/dockerhub-mirror/dynamic-api