dist: trusty
language: java
install: true

jdk:
  - openjdk8

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dynamic-api .
  - docker images
  - docker tag dynamic-api $DOCKER_USERNAME/dynamic-api
  - docker push $DOCKER_USERNAME/dynamic-api
  - docker logout
  - eval $(aws ecr get-login --region us-east-1 --no-include-email)
  - docker tag dynamic-api $ECR_REPOSITORY/dynamic-api
  - docker push $ECR_REPOSITORY/dynamic-api
  - aws ecs update-service --cluster dynamic-api --service dynamic-api --force-new-deployment
  - docker logout