dist: trusty
language: java
install: true

jdk:
  - openjdk8

script:
  - ./gradlew build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dynamic-api .
  - docker images
  - docker tag dynamic-api $DOCKER_USERNAME/dynamic-api
  - docker push $DOCKER_USERNAME/dynamic-api
  - docker tag dynamic-api $ECR_REPOSITORY/dynamic-api
  - docker push $ECR_REPOSITORY/dynamic-api